name: tvheadend
adopt-info: tvheadend
summary: TV streaming server supporting DVB, ATSC, IPTV, and SAT>IP
description: >
  Tvheadend is a TV streaming server and digital video recorder supporting
  DVB-S, DVB-S2, DVB-C, DVB-C2, DVB-T, DVB-T2, ATSC, IPTV, SAT>IP and other
  formats. It can also stream and record from HDHomeRun devices.

  Once installed use your web browser to navigate to http://<IP-Address>:9981/.
  You can use 127.0.0.1 for the IP Address if your browser and tvheadend are
  on the same computer. You can change the listening port and IP with
  `snapctl set tvheadend tvh-http-port=9981` and
  `snapctl set tvheadend tvh-ip=0.0.0.0`. You can also change the port for HTSP
  streaming connections with `snapctl set tvheadend tvh-htsp-port=9982`

  OSCam's web interface is listening on port 8888 by default. You can change
  this by editing the file returned by `tvheadend.oscam-config`. e.g.
  `sudo $EDITOR $(tvheadend.oscam-config)`. This is an ini-style file where the
  web interface IP Address and Port are configured as below:

  ```ini
  [global]
  serverip =

  [webif]
  httpport =
  ```

  See [the OSCam configuration reference](http://www.streamboard.tv/wiki/OSCam/en/Config/oscam.conf)
  for details on the accepted options for the configuration file.

confinement: strict
grade: stable
base: core18

architectures:
  - build-on: i386
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

apps:
  tvheadend:
    command: bin/tvheadend-launch
    daemon: simple
    plugs:
      - dvb
      - network
      - network-bind
      - removable-media

  tvheadend-webui:
    command: bin/tvheadend-webui
    desktop: usr/share/applications/tvheadend.desktop
    plugs:
      - desktop

  reset-permissions:
    command: bin/reset-permissions

  oscam:
    command: usr/local/bin/oscam -c $SNAP_DATA -t $TMPDIR -u
    daemon: simple
    plugs:
      - dvb
      - network
      - network-bind
      - removable-media

  oscam-webui:
    command: bin/oscam-webui
    desktop: usr/share/applications/oscam.desktop
    plugs:
      - desktop

  oscam-config:
    command: bin/get-oscam-conf

parts:
  icons:
    plugin: dump
    source: icons

  scripts:
    plugin: dump
    source: scripts

  desktop-files:
    plugin: dump
    source: desktop-files

  libusb:
    plugin: autotools
    source: https://github.com/libusb/libusb/releases/download/v1.0.22/libusb-1.0.22.tar.bz2
    configflags:
      - --prefix=/usr
    build-packages:
      - libudev-dev
    stage-packages:
      - libudev1

  oscam:
    after: [libusb]
    plugin: make
    source: http://www.streamboard.tv/svn/oscam/trunk/
    source-type: svn
    override-build: |
      MAKEOPTS="USE_LIBUSB=1 USE_PCSC=1 USE_UTF8=1 NO_PLUS_TARGET=1"
      MAKEOPTS="$MAKEOPTS OSCAM_BIN='$SNAPCRAFT_PART_INSTALL/usr/local/bin/oscam' BINDIR='$SNAPCRAFT_PART_INSTALL/usr/local/bin'"
      MAKEOPTS="$MAKEOPTS EXTRA_CFLAGS='-I$SNAPCRAFT_STAGE/usr/include/libusb-1.0' EXTRA_LDFLAGS='-L$SNAPCRAFT_STAGE/usr/lib'"
      mkdir -p "$SNAPCRAFT_PART_INSTALL/usr/local/bin"
      make $MAKEOPTS allyesconfig
      make $MAKEOPTS -j$SNAPCRAFT_PARALLEL_BUILD_COUNT pcsc-libusb
    build-packages:
      - libssl-dev
      - libpcsclite-dev
    stage-packages:
      - libssl1.0.0
      - libpcsclite1

  tvheadend:
    plugin: make
    source: https://github.com/tvheadend/tvheadend.git
    source-branch: release/4.2
    organize:
      snap/tvheadend/current/usr: usr
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        snapcraftctl set-version "$(echo "${last_committed_tag}" | sed -E -e "s!^($SNAPCRAFT_PROJECT_NAME-?|v(ersion)?[/-]?)!!i")"
      else
        snapcraftctl set-version "$(git rev-parse --short HEAD)"
      fi
    override-build: |
      CONFIGFLAGS="--arch=$SNAPCRAFT_ARCH \
        --prefix=/snap/tvheadend/current/usr \
        --enable-hdhomerun_client"
      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "arm-linux-gnueabihf" -o "$SNAPCRAFT_ARCH_TRIPLET" = "aarch64-linux-gnu" ]; then
        CONFIGFLAGS="$CONFIGFLAGS --disable-ffmpeg_static"
      fi
      ./configure $CONFIGFLAGS
      snapcraftctl build
    build-packages:
      - bzip2
      - cmake
      - gettext
      - libavahi-client-dev
      - libavcodec-dev
      - libavformat-dev
      - libavresample-dev
      - libavutil-dev
      - libc6-dev
      - libdvbcsa-dev
      - libhdhomerun-dev
      - libpcre3-dev
      - libssl-dev
      - libswscale-dev
      - libtool-bin
      - liburiparser-dev
      - libva-dev
      - python
      - wget
      - zlib1g-dev
    stage-packages:
      - bzip2
      - libavahi-client3
      - liburiparser1
      - zlib1g

      # Video Acceleration
      - libva2
      - libva-drm2
      - try:
        - va-driver-all
        - vdpau-va-driver
      # - libva-egl1
      # - libva-glx1
      # - libva-tpi1
      # - libva-wayland1
      # - libva-x11-1
