name: tvheadend
version: '4.2.6'
summary: TV streaming server supporting DVB, ATSC, IPTV, and SAT>IP
description: >
  Tvheadend is a TV streaming server and digital video recorder supporting
  DVB-S, DVB-S2, DVB-C, DVB-C2, DVB-T, DVB-T2, ATSC, IPTV, SAT>IP and other
  formats. It can also stream and record from HDHomeRun devices.

  Once installed use your web browser to navigate to http://<IP-Address>:9981/
  (You can use 127.0.0.1 for the IP Address if your browser and tvheadend are on
  the same computer.)

confinement: strict
grade: stable

apps:
  tvheadend:
    command: usr/bin/tvheadend --config $SNAP_DATA
    daemon: simple
    plugs:
      - dvb
      - network
      - network-bind

parts:
  tvheadend:
    plugin: make
    source: https://github.com/tvheadend/tvheadend/archive/v$SNAPCRAFT_PROJECT_VERSION.tar.gz
    organize:
      snap/tvheadend/current/usr: usr
    override-build: |
      CONFIGFLAGS="--arch=$SNAPCRAFT_ARCH \
        --prefix=/snap/tvheadend/current/usr \
        --enable-hdhomerun_client"
      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "arm-linux-gnueabihf" -o "$SNAPCRAFT_ARCH_TRIPLET" = "aarch64-linux-gnu" ]; then
        CONFIGFLAGS="$CONFIGFLAGS --disable-ffmpeg_static"
      fi
      ./configure $CONFIGFLAGS
      snapcraftctl build
    build-packages:
      - bzip2
      - cmake
      - gettext
      - libavahi-client-dev
      - libavcodec-dev
      - libavformat-dev
      - libavresample-dev
      - libavutil-dev
      - libc6-dev
      - libdvbcsa-dev
      - libhdhomerun-dev
      - libpcre3-dev
      - libssl-dev
      - libswscale-dev
      - libtool-bin
      - liburiparser-dev
      - libva-dev
      - python
      - wget
      - zlib1g-dev
    stage-packages:
      - bzip2
      - libavahi-client3
      - liburiparser1
      - zlib1g

      # Video Acceleration
      - libva1
      - libva-drm1
      - try:
        - va-driver-all
        - vdpau-va-driver
      # - libva-egl1
      # - libva-glx1
      # - libva-tpi1
      # - libva-wayland1
      # - libva-x11-1
