#!/bin/bash

mkdir $SNAP_DATA/accesscontrol
cat > $SNAP_DATA/accesscontrol/cd8d0804bef721c2cadef68e5ba6e44e <<EOF
{
	"index": 1,
	"enabled": true,
	"username": "*",
	"prefix": "0.0.0.0/0,::/0",
	"change": [
		"change_rights"
	],
	"uilevel": -1,
	"uilevel_nochange": -1,
	"streaming": [
		"basic",
		"advanced",
		"htsp"
	],
	"profile": [
	],
	"dvr": [
		"basic",
		"htsp",
		"all",
		"all_rw",
		"failed"
	],
	"htsp_anonymize": false,
	"dvr_config": [
	],
	"webui": true,
	"admin": true,
	"conn_limit_type": 0,
	"conn_limit": 0,
	"channel_min": 0,
	"channel_max": 0,
	"channel_tag_exclude": false,
	"channel_tag": [
	],
	"comment": "Default access entry",
	"wizard": false
}
EOF